sonar.organization=manish-gokhare
sonar.projectKey=manish-gokhare_CloudOps-Insights
sonar.projectName=CloudOps-Insights

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=static/**,templates/**,data/**